executors:
  node:
    docker:
      - image: circleci/node:10

aliases:
  restore_cache: &restore_cache
    restore_cache:
      name: Restore Npm Package Cache
      keys:
        - yarn-cache-{{ checksum "yarn.lock" }}

  install_node_modules: &install_node_modules
    run:
      name: Install dependencies
      command: yarn

  save_cache: &save_cache
    save_cache:
      name: Save NPM package cache
      key: yarn-cache-{{ checksum "yarn.lock" }}
      paths:
        - ./node_modules

version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  test:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *save_cache
      - run:
          name: Test
          command: yarn test --coverage --collectCoverageFrom=src/**/*.js --collectCoverageFrom=!src/**/*.stories.js --collectCoverageFrom=!src/utils/* --collectCoverageFrom=!src/service/* --maxWorkers=2
      - store_artifacts:
          path: coverage
      - codecov/upload:
          file: ./coverage/coverage-final.json
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and Push Docker Image
          command: |
            TAG=test.$CIRCLE_SHA1
            docker build -t oldschool-react:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push oldschool-react:$TAG

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test:
          filters:
            branches:
              only: kubernetes-google
      - build:
          filters:
            branches:
              only: kubernetes-google
