version: 2.1
orbs:
  node: circleci/node@1.1.6
  docker: circleci/docker@0.5.13
  gcp-gke: circleci/gcp-gke@0.2.0
  codecov: codecov/codecov@1.0.5
jobs:
  test:
    description: Test SPA
    machine: true
    steps:
      - checkout
      - node/install
      - node/install-yarn
      - node/with-cache:
          steps:
            - run:
                name: Install application dependencies
                command: yarn
          cache-key: package.json
          use-strict-cache: true
      - run:
          name: Test
          command: yarn test --coverage --collectCoverageFrom=src/**/*.js --collectCoverageFrom=!src/**/*.stories.js --collectCoverageFrom=!src/utils/* --collectCoverageFrom=!src/service/* --maxWorkers=2
      - store_artifacts:
          path: coverage
      - codecov/upload:
          file: ./coverage/coverage-final.json
  build-push-docker:
    description: Build and push image to Docker Hub
    machine: true
    steps:
      - checkout
      - docker/publish:
          deploy: true
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: test-$CIRCLE_SHA1
  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      - gcp-gke/install
      - gcp-gke/init
      - gcp-gke/rollout-image:
          deployment: your-first-cluster-1
          container: oldschool-spa
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:test-$CIRCLE_SHA1 # change version when updating
workflows:
  test_build_update_deploy:
    jobs:
      - test
      - build-push-docker:
          requires:
            - test
      - deploy:
          requires:
            - build-push-docker
