# Services
apiVersion: v1
kind: Service
metadata:
  name: oldschool-service
  labels:
    app: oldschool-react
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: oldschool-react
    tier: frontend
  type: LoadBalancer

---
# Apps
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oldschool-react
  labels:
    app: oldschool-react-front
spec:
  selector:
    matchLabels:
      app: oldschool-react
      tier: frontend
  replicas: 3
  minReadySeconds: 180
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: oldschool-react
        tier: frontend
    spec:
      containers:
      - name: oldschool-react
        image: kevinfaguiar/oldschool-react
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: 1Gi
            cpu: 1
          limits:
            memory: 1Gi
            cpu: 1

---
# HPA
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: oldschool-react
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: oldschool-react
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 30

---
# PDB
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: oldschool-react
spec:
  selector:
    matchLabels:
      app: oldschool-react
  minAvailable: 10%
